components:
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer token using a JWT
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Error message
    Id:
      type: string
      format: cuid
  responses:
    InvalidInput:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    NotAuthenticated:
      description: Not authenticated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    OrganizationNotFound:
      description: Organization not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
  parameters:
    organizationId:
      name: organizationId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/id'