components:
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer token using a JWT
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Error message
    Id:
      type: string
      format: cuid
    UserName:
      type: string
    Email:
      type: string
      format: email
    User:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          $ref: '#/components/schemas/UserName'
        email:
          $ref: '#/components/schemas/Email'
    Role:
      type: string
      enum:
        - MEMBER
        - ADMIN
    Organization:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          $ref: '#/components/schemas/OrganizationName'
    OrganizationName:
      type: string
    Membership:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        organization:
          $ref: '#/components/schemas/Organization'
        role:
          $ref: '#/components/schemas/Role'
  responses:
    BadRequest:
      description: The request is invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Authentication is required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'    
    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: A referenced resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Conflict:
      description: The request conflicts with the current state of the resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  parameters:
    organizationId:
      name: organizationId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Id'
    userId:
      name: userId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Id'
    projectId:
      name: projectId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Id'