components:
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer token using a JWT.
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Error message
    Id:
      type: string
      pattern: '^c[a-z0-9]{24}$'
      example: 'ch72gsb320000udmn3v7np9qq'
    UserName:
      type: string
      example: John Doe
    Email:
      type: string
      format: email
      example: john.doe@example.com
    User:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          $ref: '#/components/schemas/UserName'
        email:
          $ref: '#/components/schemas/Email'
    Role:
      type: string
      enum:
        - MEMBER
        - ADMIN
    Organization:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          $ref: '#/components/schemas/OrganizationName'
    OrganizationName:
      type: string
      example: Example Inc.
  responses:
    BadRequest:
      description: The request is invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Authentication is required.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'    
    Forbidden:
      description: Insufficient permissions.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: A referenced resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Conflict:
      description: The request conflicts with the current state of the resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  parameters:
    organizationId:
      name: organizationId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Id'
    userId:
      name: userId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Id'
    projectId:
      name: projectId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Id'